### ISSUE TITLE
關於幻影分頁(Phantom Tab)

### ISSUE THREAD

**Issue by jaxon0523** [yfdyh000/tabutils#1]
自從ff29以後好像就失效了，請問可以修正嗎?
謝謝!!!

**Comment by yfdyh000** [comment]
今天已经排查过数小时，但因为没有相关的报错信息，各种方法排除了六七处都还没找出问题原因。
我的测试结果是Fx29正常，Fx30以后开始失效。

**Comment by jaxon0523** [comment]
感謝大大的檢查
現在幻影分頁一關閉就無法再次點擊開啟，有點不方便呢

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases/tag/2015.02.12 请试用。如有问题请回报。
已知问题：
TypeError: tabContainer.tabbrowser is undefined tabbrowser.xml:4910:14   只是报错，不影响功能，暂未解决。
点击打开幻影标签页时会有瞬间闪动，因为创建和关闭标签页。在Firefox 30中测试之前的版本好像也有闪动，不知道是新问题还是旧问题，暂未解决。另外，Firefox 29和30中似乎未稳定重现问题。

题外话，browser.tabs.closeButtons [已失效](https://hg.mozilla.org/releases/mozilla-release/rev/1f5f1fe135b9)，暂未研究如何修复。

**Comment by jaxon0523** [comment]
太感謝了!!!可以使用了!!!
從30以後忍耐到現在，真的很感謝您!!!!!!
