### ISSUE TITLE
New tabs open at far end of tab bar

### ISSUE THREAD

**Issue by Keith94** [yfdyh000/tabutils#109]
In TU options I set the option `Open new tabs next to current tab which are from` to `All`, however new blank tabs always open at the rightmost position in tab bar (rather than after the current tab). I'm using Nightly 52 on Windows 8 in a clean profile.

**Comment by tyaremco** [comment]
This is also a problem in Beta 51.  Not a problem in Release 50.

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/commit/b35d6f5857da18ad28ac17c665211c165771775d fixed this.
Please wait for review of the 2016.12.27 version.
