### ISSUE TITLE
[Suggestion] Review addon by Mozilla

### ISSUE THREAD

**Issue by JohnDoeFromNorth** [yfdyh000/tabutils#11]
Hello!
Currently Tab Utilities Fixed on addons.mozilla.org is not reviewed by Mozilla. That means the extension is not visible in the search results. I think it will be easier to gain the userbase if the addon is accessible through search.

Also, AMO allows to upload unreviewed versions of addons to the beta channel. So it is possible to have a reviewed version of addon for wide audience and beta version of addon for testing and latest bug fixes.

**Comment by yfdyh000** [comment]
Mozilla reviewer is lacking, so it is still on "Queue Position: 47 of 129" after nearly a month.

And, I once selected the Preliminary Review, I just switched the to Full Review (maybe more appropriate, I'm not sure), the indicator turns to: 70 of 146...

**Comment by yfdyh000** [comment]
Verified.

https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/versions/
