### ISSUE TITLE
FF v49.0.2 ---> "Mouse scroll to focus a tab" not working...

### ISSUE THREAD

**Issue by wernerml** [yfdyh000/tabutils#114]
DAmnnnnnnnnnnnnnnn, this is a Major feature... =(

both other addons who does this,   stopped working too!!!
[Tab Kit](https://addons.mozilla.org/en-US/firefox/addon/tab-kit-mouse-gestures/),   and   [Tab Wheel Scroll
](https://addons.mozilla.org/en-US/firefox/addon/tab-wheel-scroll/)
some major change by FF...

**Comment by yfdyh000** [comment]
Dupe of #97.
