### ISSUE TITLE
Opening address or searching in the "Address bar"(Location bar) by hitting enter key doesn't open new tab on FF 50.

### ISSUE THREAD

**Issue by kissglay** [yfdyh000/tabutils#115]
After upgrading to FF50, opening address or searching in the address bar and **hitting enter** doesn't open new tab, and instead, it opens them in the current tab. ("Open new tabs for" option is properly set)
(**Using mouse** to select the entry or click the arrow icon to the right of address bar works just as expected)

**Comment by liuxb** [comment]
刚升级到50，发现有同样情况，盼修正，谢谢！

**Comment by Guil211** [comment]
Any update on that one? Thanks!

**Comment by irvinm** [comment]
Same issue here.  Hoping for a workaround or fix.

**Comment by seiry** [comment]
作者辛苦了~thank U~

**Comment by Guil211** [comment]
Thanks for the fix, I appreciate the work during this time of year. However, the issue is not fixed for me. I still get the abnormal behavior (typing in address bar, pressing Enter results in page loading in current tab instead of in a new tab). Using FF50.1.0, TU2016.12.30 (though the name of the addon is still 2016.07.31, I do see today's date in the "last updated field). As far as I can tell, the addon installed correctly (had to disable signature requirement to force FF to install), but I keep wondering. Any suggestion? Cheers,

**Comment by yfdyh000** [comment]
@Guil211 Unless you use the firefox-50.1.0.en-US.win32-add-on-devel.installer edition, otherwise you can‘t install an unsigned addon on Fx50.1.0. I guess you did not get this latest version and I confirmed it to display the correct version in Add-ons Manager - it's details.

**Comment by yfdyh000** [comment]
p.s. Queue Position: 61 of 121 on AMO review.

**Comment by Guil211** [comment]
That explains it, thanks. I thought I had managed to force the install, but looks like not. Any timeline to have it signed then? :)

**Comment by yfdyh000** [comment]
I am also waiting, because I use the Beta channel. Queue Position: 54 of 115. There is no expected time.

If you are anxious to use it, auto-signing an unlisted add-on is probably feasible on AMO, using another UUID and no auto-update.

**Comment by habmalnefrage** [comment]
Waiting too for signed tabutils as on FF 50 unsigned add-ons will not install even with xpinstall.signatures.required being set to false in about::config

**Comment by habmalnefrage** [comment]
an excellent workaround for unsigned add-ons:
http://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/

**Comment by Guil211** [comment]
Rejoice! The signed version has made its way through and is available on AMO/extension update.
@habmalnefrage thanks for the link, I'll keep it in mind for next time. Thanks again @yfdyh000 for the update, and cheers!
