### ISSUE TITLE
全部标签添加书签失败

### ISSUE THREAD

**Issue by withero** [yfdyh000/tabutils#116]
Fx50  全部标签添加书签失败，添加后新建目录夹，但是标签并未添加进去，目录夹为空。

**Comment by abchb99** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/bookmark-current-tab-set/
安装这个后，书签菜单增加全部标签加书签的项目，可用。

**Comment by yfdyh000** [comment]
Dupe of #110.
