### ISSUE TITLE
e10s 模式鼠标中键点击链接工作不正常 

### ISSUE THREAD

**Issue by ryans233** [yfdyh000/tabutils#117]
版本为 Firefox Developer Edition 51.0a2，启用 e10s 后中键点击网页链接总是会在前台新标签页打开，更改扩展设置无效。禁用该扩展或禁用 e10s 则恢复为后台新标签页打开。
期望效果为中键点击链接时跟随扩展设置，或者跟随原生 Firefox 设置在后台新标签页打开。

**Comment by yfdyh000** [comment]
Dev note: https://github.com/yfdyh000/tabutils/blob/cd8c8c5d680e7c7a380475ba40bb662253dcc5ba/chrome/content/utilityOverlay.js#L5
It got `ContentClick.contentAreaClick` for links.

Options - Mouse - Middle - Bookmarks (and othes?) also be affected in e10s turn on. `PUIU_openNodeWithEvent`.
