### ISSUE TITLE
Pinned tabs appear on top of regular tabs

### ISSUE THREAD

**Issue by hackel** [yfdyh000/tabutils#12]
This may have been related to 4da116fbbf42b9d3ab89a4ce68f29d5a76408d02.  When I pin a tab, my non-pinned tabs move all the way to the left, and the pin tab appears on top of them, with it's icon actually appearing to the right of the unpinned tab beneath it.

**Comment by yfdyh000** [comment]
Multi-line Tabbar enabled? I see the similar problem on Fx28 + Original TU, so this is a bug / feature in Original TU?
I saw the pinned tabs occupation a separate line when the Multi-line Tabbar option enabled and the non-pinned tabs width overflow.

Can you attach a screenshot? I don't understand the "with it's icon actually appearing to the right of the unpinned tab beneath it."

**Comment by hackel** [comment]
No, I don't use the multi-line tabbar.  I beleve it was present in the original TU as well, once Australis came out.

![pinned tab](https://cloud.githubusercontent.com/assets/583677/6569786/354ada12-c6be-11e4-8fb6-73f7532961da.png)

In the first image, I have the pinned tab (gmail icon) selected.  Second image, the first non-pinned tab is selected (regular google icon), and third, another tab is selected, and you can see the icon placement.  If I enable the "Left extra space" option, then both icons line up on top of each other.

**Comment by yfdyh000** [comment]
Thanks for the report, I see the problem when switching the "Left extra space" option.

**Comment by hackel** [comment]
Sorry, just want to clarify, in the screenshots above, the "left extra space" option was _not_ enabled.  I was saying that if I do turn it on, then both icons appear exactly horizontally aligned.  Oddly, at the moment it seems to have fixed itself and my pinned tab (now added a second) are working perfectly. Unless you pushed a new version I didn't notice!

**Comment by yfdyh000** [comment]
Thanks for the added, I did not to push a new version (and currently it cannot be silent update).

I see the problem when enabled the option, pin a tab, then disable the option, in seems any Firefox + any TU. The issue will be temporarily eliminate if I press the `Alt` key to trigger the menu bar, or call the `this.positionPinnedTabs()` a.k.a. `gBrowser.mTabContainer.positionPinnedTabs()`

**Comment by spvkgn** [comment]
I have the same issue with latest release 2015.03.09-fix
with previous version 2015.02.19-2 this issue does not occurs. FF33

![tabutils-pinned](https://cloud.githubusercontent.com/assets/4147135/6728808/9412f81c-ce4e-11e4-9f40-30e935f9f9d4.png)

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases/tag/2015.07.06
