### ISSUE TITLE
安装TUF并开启多进程后，页面右键菜单弹出有明显延迟

### ISSUE THREAD

**Issue by liuxb** [yfdyh000/tabutils#121]
firefox50，新建配置，只安装tuf，设置extensions.e10sBlockedByAddons;false。
这时在有些页面中点空白处右键菜单弹出有明显延迟，每次都是，比如http://bbs.kafan.cn/forum-215-1.html，有些影响比较小，如https://github.com/yfdyh000/tabutils/issues/new。
如设置extensions.e10sBlockedByAddons;true，所有页面都没延迟（第一次可能有点，随后每次就都好了）。

另，在关闭e10s后，重启打开http://bbs.kafan.cn/forum-215-1.html，第一次右键弹菜单时任然有迟钝，但随后每次都秒开了。开e10s，每次都很慢。 

07.31，12.27都有这问题，其他没试

**Comment by yfdyh000** [comment]
感谢报告。看到了延迟。//浏览区右键菜单 的 isLinkSelected，需要耗时300ms。

**Comment by yfdyh000** [comment]
Fixed in 2017.01.30, please check it.

**Comment by liuxb** [comment]
多谢修复，第一时间试用了。
发现弹出缓慢的问题解决了。
就是每次启动firefox后，第一次在页面空白区点击右键的时候，弹出菜单总会闪（收缩）一下，研究了下发现先谈出来的菜单中有一个菜单项“Open Selected Links in New Tabs []”，然后然后这一项消失，变成正常菜单，这个过程中会闪一下。
不知是否是正常情况？
抓图[http://i.imgur.com/coQLtoY.png](url)            [http://i.imgur.com/Sk4Wjc2.png](url)
祝春节快乐:)

**Comment by yfdyh000** [comment]
@liuxb 是已知情况。我这里不是很明显，消失通常迅速。尚未发现怎么避免闪烁。

**Comment by yfdyh000** [comment]
2017.02.04中已做改善，仅在选中多个链接时闪一下。
`tabutils.addEventListener(window, "popupshown"` 不知道能否用于改善，尚未尝试。
