### ISSUE TITLE
Mouse scroll to focus a tab advances two tabs at a time (to reopen issue #112)

### ISSUE THREAD

**Issue by erdemuncuoglu** [yfdyh000/tabutils#122]
Also it is mentioned that #112 is duplicate of #97 but mouse scroll still advances 2 tabs at once. I'm using FF 51.0b5 (64-bit) on Debian 8. The solution seems to be "event.preventDefault();" as I mentioned before. I will post an other pull request for that.
P.S. I'm not so experienced in FF add-on development but the other add-on devs used that solution for similar issues.

**Comment by apogrebennyk** [comment]
@yfdyh000 could you please include it into next upgrade? This is affecting me as well. Currently have to run the nightly build to install unsigned add-on with this fix.
