### ISSUE TITLE
SuperStart起始页无法 “Ctrl+左击”群组，后台打开标签页

### ISSUE THREAD

**Issue by MalcKear** [yfdyh000/tabutils#125]
同样中键点击群组也无法后台打开标签页

**Comment by yfdyh000** [comment]
能具体说一下吗。Super Start 7.4.0.1+TUF 2017.01.27，TUF启用与否好像没什么区别：
中键单击群组则后台新建Super Start标签页。Ctrl+单击为后台打开群组。

或请检查是否与TUF的选项（选项对话框左下角，恢复默认设置）或其他扩展有关。

**Comment by MalcKear** [comment]
问题找到了
extensions.tabutils.reuseBlank;2
但是不知道是多久前的参数，具体功能也不知道

**Comment by yfdyh000** [comment]
就是坏了很久没修好的打开时替换空白页功能。
Dupe of #96.

**Comment by MalcKear** [comment]
`extensions.tabutils.menu.context_copyTabTitleAndURL;true
extensions.tabutils.menu.context_copyTabTitleAndURL.accesskey;C
extensions.tabutils.menu.context_copyTabTitleAndURL.insertbefore;context_ungroupTab
extensions.tabutils.menu.context_copyTabTitleAndURL.label;复制页面标题和URL
extensions.tabutils.menu.context_copyTabTitleAndURL.multiselected;any
extensions.tabutils.menu.context_copyTabTitleAndURL.oncommand;Cc['@mozilla.org/widget/clipboardhelper;1'].getService(Ci.nsIClipboardHelper).copyString([tab.label + ' - ' +tab.linkedBrowser.currentURI.spec for (tab of gBrowser.mContextTabs)].join('\n'));`
在标签页右键菜单添加复制标题和URL功能，希望可以修复下
以下几个快捷键功能也失效了，最常用的就是Ctrl +C ,Ctrl + V
Keyboard shortcuts:
Ctrl+C: Copy Page Location
Ctrl+X: Copy Page Location and Close Tab
Ctrl+V: Paste and Go
Ctrl+Shift+V: Paste and Search

**Comment by yfdyh000** [comment]
这个代码是怎么用，格式乱了吗。

快捷键好像都失效了，今天刚查过，没找到失效成因。
与版本、e10s状态、当前页面类型好像都相关，在少数页面上偶尔正常。已记在 #107。

**Comment by MalcKear** [comment]
`user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL", true);
user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL.accesskey", "C");
user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL.insertbefore", "context_ungroupTab");
user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL.label", "复制页面标题和URL");
user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL.multiselected", "any");
user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL.oncommand", "Cc['@mozilla.org/widget/clipboardhelper;1'].getService(Ci.nsIClipboardHelper).copyString([tab.label + ' - ' +tab.linkedBrowser.currentURI.spec for (tab of gBrowser.mContextTabs)].join('\\n'));");
`
直接自定义pref.js文件

**Comment by yfdyh000** [comment]
@MalcKear `user_pref("extensions.tabutils.menu.context_copyTabTitleAndURL.oncommand", "Cc['@mozilla.org/widget/clipboardhelper;1'].getService(Ci.nsIClipboardHelper).copyString([for (tab of gBrowser.mContextTabs) tab.label + ' - ' +tab.linkedBrowser.currentURI.spec].join('\\n'));");`
`for...of`倒过来。

**Comment by MalcKear** [comment]
@yfdyh000 3Q
