### ISSUE TITLE
安装扩展后，开启平滑滚动，滑动网页会卡

### ISSUE THREAD

**Issue by xsjhqj** [yfdyh000/tabutils#135]
adm速龙iiX4 640的u，已自行在另外一台i3的pc上测试没有问题。安装的几款扩展中，有一两款扩展也会出现相同的情况。网页一跳一跳的。已知Tab Mix Plus 、right_click_close有类似问题。但在另外一台pc上则完全不存在。打开硬件加速勉强可用，但还会有些卡。不开加速的情况下，根本没法用。

**Comment by yfdyh000** [comment]
能否新建一个配置文件，并且仅安装TUF，重现此问题？
如果其他扩展也导致，可能是Firefox的bug。可以去卡饭问问。

**Comment by xsjhqj** [comment]
也试过只安装此款扩展，问题一样存在。

**Comment by yfdyh000** [comment]
只安装其他扩展呢？如果也有问题的话，就非TUF问题。我没遇到过。
其他PC无问题，或许是系统/显卡问题？开始-运行`dxdiag`，“显示”里的各项加速如何。
旧版本Firefox有问题吗。https://ftp.mozilla.org/pub/firefox/releases/ 有各版本下载。

**Comment by yfdyh000** [comment]
有看到卡饭的帖子。不像是TUF的问题。
