### ISSUE TITLE
開啟外部連結為分頁功能失效

### ISSUE THREAD

**Issue by jaxon0523** [yfdyh000/tabutils#138]
開啟e10s之後，「開啟外部連結於：新分頁」功能失效

開啟外部連結變成新視窗開啟

開啟「強制以新分頁開啟所有外部連結」功能，會變成新分頁開啟，但還是會彈出新視窗

感謝大大的維護！

**Comment by yfdyh000** [comment]
Dupe of #101.
已调查并有线索，但未理解如何解决。
