### ISSUE TITLE
ReloadEvery fires once only

### ISSUE THREAD

**Issue by NickJH** [yfdyh000/tabutils#140]
Hi, I'm so glad to have this extension back!

Typically I load a bookmark folder of 4 tabs. The first tab is a dummy tab, bet the 2nd, 3rd and 4th open with ReloadEvery activated and the second and third open locked. The fourth tab is https://www.clearos.com/clearfoundation/social/community and it looks like reloadevery works once and then does not fire again. If I change the interval to 30s it again works once then no more. Using 1.5.2017.02.04 on Ff 51.0.1 (32-bit) on Win10 x64

Nick

**Comment by yfdyh000** [comment]
Dupe of #95.
