### ISSUE TITLE
打开网页新建标签页的问题，还有快捷键的问题

### ISSUE THREAD

**Issue by star2056** [yfdyh000/tabutils#148]
我之前用的FF28，原版TU有个我很喜欢的设定
就是如果当前页面是空白标签页，输入地址回车后会立刻打开
如果当前页面是有内容的标签页，输入地址回车后会新建一个标签页打开

换了FF40以后，TU已经不能用了，我去addon firefox看了一下，找到了您的扩展
下来以后发现不管怎么设置都没办法实现我所说的功能
要么就是所有链接强制打开一个新的标签页（即使我已经打开了一个空白标签页，这样我还要关掉，很麻烦）
要么就是跟原版FF一样，输入地址回车后，不小心覆盖了我之前在看的网页
请问这个要怎么设定才能变成我上文说的那种情况呢？

另外原版TU还有个不错的功能是自动识别剪切板内的内容
比如我在记事本复制了一段URL
我打开FF，直接在窗口按下Ctrl+V就能打开对应的网页
请问这个功能您的TUF有吗？

我只是单纯想要询问是否有对应的功能以及如何调整能够实现，绝对不是催作者您。还请不要误会，并希望您能抽空帮忙解答一下，谢谢！

3.28 17:50补充：我下载的是1.5.2017.02.04版本

**Comment by yfdyh000** [comment]
都有，但新版中都坏掉了。前者试了几次都修不好，后者也还找不出原因。
前者 Duplicate of #131.
后者 Duplicate of #107.

因为很多功能找不出修复的方法、缺乏帮助，以及Firefox 57将只有WebExtension，所以近期没有修复开发的计划。

**Comment by star2056** [comment]
好的，非常谢谢您的答复
