### ISSUE TITLE
请问 "复制当前标签页地址" 的功能是不是取消掉了?

### ISSUE THREAD

**Issue by uqiu** [yfdyh000/tabutils#160]
请问 "复制当前标签页地址" 的功能是不是取消掉了?

**Comment by yfdyh000** [comment]
TU没有这个功能吧。

**Comment by uqiu** [comment]
http://tieba.baidu.com/p/4139863686   应该是有这个功能的,但是这个扩展我也是很多年前开始用的,细节就真记不清了  这个帖子还有我的回帖,也是某次更新之后那个功能失效,后来不知道怎么的又搞好了

**Comment by uqiu** [comment]
我又搜了一下,好像可以用这段代码配合keyconfig实现,OK 结贴

`var gClipboardHelper = Components.classes['@mozilla.org/widget/clipboardhelper;1'].getService(Components.interfaces.nsIClipboardHelper);
gClipboardHelper.copyString(window._content.location.href);`

**Comment by yfdyh000** [comment]
想起是有一个页面上Ctrl+C的功能，失效了。dupe of #107.
`extensions.tabutils.shortcut.tuClipboardKeyset.disabled`
