### ISSUE TITLE
Automatic Updates for the fork?

### ISSUE THREAD

**Issue by FatOrangutan** [yfdyh000/tabutils#2]
Can your addon installed from GitHub update itself every time you release a new version?
If not, could you please consider using the official addon repo?

**Comment by yfdyh000** [comment]
Hi, thanks for your advice, I recently had the prepare to publish it to AMO.
Expected name: Tab Utilities Fixed.
I hope it is appropriate for the English grammar.

**Comment by yfdyh000** [comment]
Published to https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/

**Comment by FatOrangutan** [comment]
Thank you!
