### ISSUE TITLE
First tab shifted left

### ISSUE THREAD

**Issue by Fossius** [yfdyh000/tabutils#21]
Look screenshot http://jpegshare.net/be/50/be5052a3d8e2794f9d534a247895641e.jpg.html

**Comment by yfdyh000** [comment]
Thanks for the report. Reproduced by pin two tabs and unpin one tab in Firefox 28.0 with 2015.03.30, not in 2015.02.19-2. The like #12, I need to consider its situation.

And a little digression, what is your version of Firefox? if it is Firefox 28 or earlier, I guess the original TU version should be sufficient.

**Comment by Fossius** [comment]
Firefox 36.0.4, 37 with Classic Theme Restorer

**Comment by yfdyh000** [comment]
Thanks for this information.

**Comment by Fossius** [comment]
Your fix of  Tab Utilities 1.5.28.1 work well in Firefox 36.0.4, but now it's incompatible

**Comment by yfdyh000** [comment]
#12 fixed
