### ISSUE TITLE
Mouse double-click action is incorrect

### ISSUE THREAD

**Issue by firekod** [yfdyh000/tabutils#24]
Options -> Mouse
L-click -> On tab bar -> New tab
Double-click -> On tab bar -> Load URL from Clipboard

When you Double-click action also perform L-click,
simultaneously open New tab and Load URL from Clipboard in another tab.

**Comment by yfdyh000** [comment]
Try change the "With a delay of" (`extensions.tabutils.leftClickTabDelay`) to 250 (default) or a higher value maybe to solve the problem you encounter.

**Comment by firekod** [comment]
Thanks you! Does this work!
