### ISSUE TITLE
Tabs and arrow appear behind pinned tabs and tab height becomes huge after dropdown from other addon..

### ISSUE THREAD

**Issue by e-motiv** [yfdyh000/tabutils#26]
![tabutfixproblems](https://cloud.githubusercontent.com/assets/2170188/7540316/9cdb52ba-f5ad-11e4-93dc-83f8912b058d.png)
Problem 1: If I open a dropdown from another addon, the tabbar becomes huge (vertically). AFter that I am stuck.
This does not happen after uninstalling TabUtFix.

Problem 2: The normal tabs appear behind pinned tabs (including the arrow to go left if too many tabs)

See screenshot. (First arrow to the left points wrongly though.)

**Comment by yfdyh000** [comment]
- I did not see the first problem, what is your extension provide the tab list, and can you try using a clean profile to reproduce it (without theme).
  - or, try use `extensions.tabutils.showTabCounter` without another addon.
- For the second problem, yes, it is a known problem. #12

**Comment by e-motiv** [comment]
I've given up on this addon for a while for lack of time. So, sorry that I can't give more information than below. (For the record I just debugged 2 other addons with firefox reset and I'm a bit tired of it. :-/).  (I just wanted to give this feedback. Don't think bad of me. ;-) )

The addon with the dropdown is called Tab Groups Helper.

**Comment by yfdyh000** [comment]
I did not see a similar interface or problem with the https://addons.mozilla.org/firefox/addon/tab-groups-helper/.

**Comment by e-motiv** [comment]
I'm just hinting it might have something to do from within tabutils in combination with addons with dropdowns.. (placed nextto the tab bar of course).

**Comment by yfdyh000** [comment]
I don't see the situation if an dropdown opened in tabbar.

**Comment by yfdyh000** [comment]
#12 fixed
