### ISSUE TITLE
File dialog does not appear

### ISSUE THREAD

**Issue by Jellby** [yfdyh000/tabutils#27]
I'm using Tab Utilities Fixed 1.5.2015.03.09-fix. Everything was fine, but I upgraded to Firefox 38.0 and now I cannot get the file dialog (If I select "save target as", or just click on a file link and then choose save file). From a terminal, I get this:

```
*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: win is undefined
Full stack: TU_getFileAsync@chrome://tabutils/content/tabutils.js:612:1
nsUnknownContentTypeDialog.prototype.promptForSaveToFileAsync/<@resource://gre/components/nsHelperAppDlg.js:295:1
TaskImpl_run@resource://gre/modules/Task.jsm:330:41
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:867:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:688:37

*************************
```

With Tab Utilities Fixed disabled, all is fine again.

I'm using Kubuntu 14.04, and I normally see KDE file dialogs, so I probably did (long ago) as explained in http://askubuntu.com/questions/119489/how-to-use-kde-dialogs-in-gtk-apps I do indeed have firefox-kde-support installed.

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases 2015.03.14 and newer fixed this issue.

**Comment by Jellby** [comment]
Thanks for the quick reply and for keeping Tab Utils up to date. And sorry for not checking for newer versions, I intended do that but forgot while writing the report... and I somehow assumed that I would be notified of new versions by firefox too. I tried with the latest version and indeed it's fixed :)
