### ISSUE TITLE
Broken in Nightly

### ISSUE THREAD

**Issue by Keith94** [yfdyh000/tabutils#3]
After installing "Tab Utilities Fixed" in a clean profile in Nightly, the browser is not able to start correctly, outside of safe mode. It only appears in Task Manager as a background process. I didn't check stable release of Firefox, just Nightly with e10s disabled.

**Comment by yfdyh000** [comment]
Thank you for your report, I also see this problem in Firefox 37 (Aurora). I will look for this problem, but there is no clue that it does not throw an error.
Also, the second start seem to be able to open a browser window, but there are still have the process residues problem when exiting browser.

**Comment by yfdyh000** [comment]
3ce96c9b651a96153a9369bb193c89cc5a397e27 fixed this.
https://github.com/yfdyh000/tabutils/releases/tag/2015.02.19-2

**Comment by Keith94** [comment]
Thanks for the fix. Seems like an odd bug.
