### ISSUE TITLE
Bookmarks disabled in Firefox 40

### ISSUE THREAD

**Issue by hackel** [yfdyh000/tabutils#31]
I'm running Tab Utilities Fixed 1.5.2015.04.05 in Firefox 40.0a2 (2015-06-23).  I can not create or clear bookmarks from either the toolbar or hitting Ctrl-D.  I can still add/edit bookmarks from the Library All Bookmarks window.  If I disable Tab Utilities, the functionality is restored.  I can't imagine what they have to do with each other, cannot see any other explanation.

**Comment by yfdyh000** [comment]
Confirmed, but I did not have enough time to study it at the moment, sorry.

**Comment by yfdyh000** [comment]
@hackel https://github.com/yfdyh000/tabutils/releases 2015.07.03.1

**Comment by hackel** [comment]
Thanks, confirmed working again. Nice work!
