### ISSUE TITLE
FF39 ignoring blank pages when open from address bar

### ISSUE THREAD

**Issue by dachacha** [yfdyh000/tabutils#32]
Greetings!
I'm not sure if it's Tab Utilities problem or not, feel free to ignore this post if it's not.

In FF38 when you open pages from address bar it replaces current blank page. But in FF39 Blank pages are ignored and it opens the page in new tab next to the blank. That's a bit annoying.
Opening from bookmarks works fine by the way, just like it was before.

Thanks anyway! Love the addon

**Comment by yfdyh000** [comment]
I think this issue is already fixed in 2015.04.05 and all of newer release, can you provide more information about it?

p.s. try set **extensions.tabutils.openUrlInTab** to `false` in about:config.

**Comment by dachacha** [comment]
No no, extensions.tabutils.openUrlInTab should be true, I have all boxes checked in this section http://i.imgur.com/IWJmZjU.png
Here's short video http://www.youtube.com/watch?v=r9Q1t7rsMiQ
In FF38 it will replace blank tab instead of opening new next to blank (no matter if extensions.tabutils.openUrlInTab is true or false, but I want it enabled).

**Comment by yfdyh000** [comment]
Um, for `extensions.tabutils.reuseBlank`, I cannot guarantee that it is works fine at the moment, so sorry :(

**Comment by yfdyh000** [comment]
Fixed in 2017.02.04, please check it.
