### ISSUE TITLE
“紧邻当前标签页打开来自以下项目的新标签页-除新建标签页以外”无效

### ISSUE THREAD

**Issue by Gzxhwq** [yfdyh000/tabutils#34]
选择“紧邻当前标签页打开来自以下项目的新标签页-除新建标签页以外”，新建标签页依然是紧邻当前标签页打开，不是在末尾打开新建标签页。

Firefox 39.0
Tab Utilities Fixed 2015.07.06

**Comment by yfdyh000** [comment]
感谢报告，https://github.com/yfdyh000/tabutils/releases/tag/2015.07.18 已修复
