### ISSUE TITLE
安装了7.18版本，36.0.4下，标签栏的颜色设置都失效了。

### ISSUE THREAD

**Issue by ruleroller** [yfdyh000/tabutils#36]
退回到7.6版本的，又恢复了。

**Comment by yfdyh000** [comment]
你好，感谢报告。还有收到另一个英文的邮件报告，也是类似的情况。
但是我尝试了Firefox 36或40+0718版本，启用所有TU选项，修改颜色设置，重启浏览器，都并没有看到这样的情况。而且0718的变更不多，并没有看到疑似的情况。

另外，现在是三份报告了，但是我还没看到原因，先等待一下吧。

**Comment by yfdyh000** [comment]
fixed in 2015.07.20.xpi on https://github.com/yfdyh000/tabutils/releases/tag/2015.07.18
#38
