### ISSUE TITLE
Tab 'unloaded' (or any other custom) style is not applied on browser start

### ISSUE THREAD

**Issue by fix-fix** [yfdyh000/tabutils#38]
Regression in version 2015.07.18
Steps to reproduce:
1. Open 'TabUtils settings -> Appearance -> Tabs'
2. Enable style for 'Current' tab
3. Restart the browser

Expected: style for 'Current' tab is applied
What happens instead: current tab has default style

---

Maybe it is affected by this change: https://github.com/yfdyh000/tabutils/commit/db510a753e12d5f8c538dd1c1ce9c2fa8dcd4c88, because elements' ids were changed and some code logic is now broken.

However if you go to 'TabUtils settings -> Appearance -> Tabs' and turn tab style off and then turn it back on, it will work as intended, so current CSS styles are working.

**Comment by yfdyh000** [comment]
Hello, thank you for mention this, I have seen three related reports today.
But I have not reproduce to this situation until now, comprising the steps you just mentioned.
If you have more clues or discovery, please tell me, thank you.

**Comment by fix-fix** [comment]
Thanks for quick response. I will try to reproduce this bug on new profile later.

Also after the same update the tab context menu shows all possible actions instead of ones specified in settings.

**Comment by yfdyh000** [comment]
Ok. if you copy and publish any error in the browser console, I guess it would be helpful.
https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

**Comment by yfdyh000** [comment]
the commit's code note:
These menupopup's is removed in 'context'.
These 'statusbar' to 'toolbarpalette' I guess does not cause problems.
These 'class' changes is a bug, I have planned to fix in the next release.

**Comment by fix-fix** [comment]
You didn't have this problem because You had toolbar buttons somewhere on your bars.
#39 fixes the issue for me.

**Comment by yfdyh000** [comment]
Looks good, and I just reproduce the issue.
Seems I had not really to hide it through customizing and restart, I missed something.

**Comment by yfdyh000** [comment]
fixed in 2015.07.20.xpi on https://github.com/yfdyh000/tabutils/releases/tag/2015.07.18

p.s. I know the current versions management may be very confusing, but I don't have a definite idea, such as a purely ordinal.
