### ISSUE TITLE
All broken in Firefox 42.0a2

### ISSUE THREAD

**Issue by hackel** [yfdyh000/tabutils#42]
Just installed the 2015.07.20 release on Firefox Developer Edition 42.0a2 (2015-08-17).  Menu entries are gone.  If I click on preferences from the list of Addons, I get the following error in a popup window:

```
XML Parsing Error: undefined entity
Location: chrome://tabutils/content/preferences.xul
Line Number 22, Column 1:<prefwindow id="tabutils-preferences"
```

**Comment by yfdyh000** [comment]
Fixed, see https://github.com/yfdyh000/tabutils/releases/tag/2015.08.18
