### ISSUE TITLE
Unable to install latest release due to add-on signing enforcement in Firefox 42.0a2

### ISSUE THREAD

**Issue by ghost** [yfdyh000/tabutils#43]
Add-on signing is now enforced: https://www.mozilla.org/en-US/firefox/42.0a2/auroranotes/

**Comment by yfdyh000** [comment]
Change the `xpinstall.signatures.required` to false and then install the add-on.

**Comment by yfdyh000** [comment]
I have no other way, because the AMO reviews process is still not completed.

**Comment by ghost** [comment]
That's a bummer.  I will make the configuration change.  Thanks for the
quick response!

## 

Tuyen Tran
(919) 515-3479

**Comment by yfdyh000** [comment]
Verified.

https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/versions/
