### ISSUE TITLE
反馈：重用空白标签extensions.tabutils.reuseBlank功能不正常

### ISSUE THREAD

**Issue by liuxb** [yfdyh000/tabutils#44]
版本fx40.02，tufixed 08.18
设置extensions.tabutils.reuseBlank为4，以下两种情况都无法重用空白页
1 当前窗口有标签，无空白标签。按ctrl+n，新开一个空白标签，此时点击书签按钮菜单中书签/地址栏下拉列表项，均无法重用那个空白标签。
2 设置fx开启时，只开始一个空白页，重启，会有一个空白标签。此时，点击地址栏下列列表项/地址输入url回车，均无法重用空白标签。
这个问题能解决吗，谢谢！
另外，这个设置没有界面，作者能不能解释下，设置1，2，4都分别是什么意思啊？多谢！

**Comment by yfdyh000** [comment]
对于 reuseBlank 功能，印象中曾几次修复，但暂时仍不能确保它工作正常，所以我目前关掉它（=0）。#32

根据 https://forum.moztw.org/viewtopic.php?f=11&t=29296&start=120 ，1，2，4 分別代表復用當前空白頁、尾部空白頁以及所有空白頁，以後會簡化成 1 個值，只重用當前空白頁。

**Comment by kidzgy** [comment]
好可惜啊，一天没修复，我一天就停留在37了。。。

**Comment by mlings** [comment]
39版本以上的，就不能重用了，现在停留在38版本，期待修复阿

**Comment by yfdyh000** [comment]
2017.02.04 中已修复。
