### ISSUE TITLE
Skip invisible links in 'open selected links in tab' function

### ISSUE THREAD

**Issue by Splitthof** [yfdyh000/tabutils#45]
Please skip invisible links (blocked by Adblock) in the 'open selected links in tab' feature.
I have achieved this by editing the isLinkSelected function:

``` javascript
isLinkSelected = function() {
...
    for (let link of links) {
      if (selection.containsNode(link, true) && (link.offsetHeight>0) && this.linkURLs.indexOf(link.href) == -1)
        this.linkURLs.push(link.href);
```

Maybe a check on link.offsetWidth>0 is also useful.
Please accept this adjustment in your code, so I no longer need to edit your code (mozilla addon signing).

**Comment by yfdyh000** [comment]
Sorry for delay, my email backlog recently.

Looks good, works for ABP element blocker.
p.s. uBlock looks removes the invisible links from DOM.

I still don't got a AMO approval and signature, and the is a micro change, so this commit will not be release immediately.
