### ISSUE TITLE
Issue with bookmarks in latest Nightly

### ISSUE THREAD

**Issue by Mazzibig** [yfdyh000/tabutils#50]
On several latest Nightly FF builds i has trouble with open bookmarks.
Error message in browser console:

```
12:40:23.858 TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
PUIU_openNodeIn() tulib.js line 105 > eval:2
PUIU_openNodeWithEvent() tulib.js line 105 > eval:3
BEH_onCommand() browser.js:5974
oncommand() browser.xul:1
1 tulib.js line 105 > eval:2:5
```

**Comment by Mazzibig** [comment]
All works fine. Bug fixed.

**Comment by yfdyh000** [comment]
Thank you for your feedback.

**Comment by rjameson3** [comment]
Not sure if you are still keeping this add-in alive, but in FF43b/64bit - you cannot click the left history arrow and jump to a page.   When I turn this add-in off, it works.   I have seen this behaviour in past versions where pages do not come up when you type from address bar - so may be similar.

**Comment by yfdyh000** [comment]
@rjameson3 Thank you for your report, I have seen this problem.
Sorry for the delay, I still need time to study it.
A workaround version (unsigned): https://github.com/yfdyh000/tabutils/releases/tag/2015.11.14

**Comment by rjameson3** [comment]
When I tried to load your unsigned – FF does not let me load it.   I recall in 42 +  the past work arounds to let it load do not apply…so I guess I will wait till you get the signed one.

Ron

**Comment by yfdyh000** [comment]
@rjameson3 Change the xpinstall.signatures.required to false in about:config.

**Comment by rjameson3** [comment]
Ok – I was able to load your test one – but problem still exists right clicking the back arrow and going into history does not.    Wasn't sure if your workaround aimed at that – so I will keep checking back to see when you post some further updates.    Thanks for your efforts, it is a great utility.
