### ISSUE TITLE
F11全屏后，鼠标移动到最上方不会弹出标签栏等

### ISSUE THREAD

**Issue by kidzgy** [yfdyh000/tabutils#55]
没安装扩展时，F11全屏后，鼠标移动到最上方，会有标签栏的。

装了扩展后，移动到最上方无反应。

FF37，TU0912。已排除过样式及其他扩展。是TU本身问题。

**Comment by yfdyh000** [comment]
感谢报告，是已知问题。
曾经修过一次，不过后续版本和修过的版本好像又有问题了，不明原因。
暂无进展。

dupe of #51.
