### ISSUE TITLE
[improvements] "Open All in New Tabs" 

### ISSUE THREAD

**Issue by tyaremco** [yfdyh000/tabutils#61]
**1)** I'd like to request a modification to the context menu item "Open All in New Tabs".  

| text selected? | behavior |
| --- | --- |
| yes | open all URLs in selected text |
| no | ~~menu item hidden~~<br/>_open all URLs in clipboard text_ |

Opening URLs from the clipboard would be very useful when needing to open a list of URLs stored outside of the browser.  

<br/>

**2)** The context menu item "Open All in New Tabs" should open tabs in an unloaded state (ie. in the same way as the Firefox option "Don't load tabs until selected"). This would greatly speed up the process of opening multiple tabs at once.

<br/>

**Note:** "Open All in New Tabs" seems to appear only when the Multiple Tab Handler extension is also installed.  However, this menu item is a feature of TU, not MTH.

**Comment by yfdyh000** [comment]
Nope, I don't find this menu exists in the TU or Firefox, nor coming from MTH.
It is likely from the TextLink[[1]](https://github.com/piroor/textlink/blob/2e828cc2cea605b0c81ced259b74d53e993f2b82/locale/en-US/textlink/textlink.dtd#L43), check your extensions and reach the right project:
https://github.com/piroor/textlink/issues

**Comment by tyaremco** [comment]
Yep, you're right.

**Comment by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [comment]
hmm... let me try to summarize both comments:

> Nope, I don't find this menu exists in the TU or Firefox, nor coming from MTH.

or perhaps @tyaremco talks about `context-openselectedlinksintab` from `<menupopup id="contentAreaContextMenu">`, which triggers on multiple urls selection (`focusedWindow.document.links` + `focusedWindow.getSelection()` + `let` + `selection.containsNode()` etc.) and which is certainly buggy (quick case: set to `false` your `dom.event.contextmenu.enabled`, open https://rawgit.com/eight04/linkify-plus-plus/master/demo/demo.html and select "http://www.example.com" + "http://www.example.com/test/" - tabutils suggests "Open Selected Links in New Tabs [2]", ditto for "http://www.example.com." + "http://www.example.com/test/.", but in case of "http://www.example.com" + "http://www.example.com." + "http://www.example.com/test/" it shows _just_ two urls in brackets)

> TextLink

well, generally, I don't know what you thinking about additional features, but anyway just note, that, as for me, it is not a very good idea to become one of this type of link detectors and that firefox have similar basic mechanism for simple one-line selection (buggy, e.g., https://addons.mozilla.org/en-US/firefox/addon/bug694856open-selected-text/ and, of course, this fix is buggy too and, afair, triggering on any selection with space on end)

> open all URLs in selected text

already here. optionaly you can easily create `context-copyselectedlinks` with something like `Services.nsIClipboardHelper.
copyString(this.linkURLs.join('\n'))`, but for pasting you need something else

> open all URLs in clipboard text

https://addons.mozilla.org/en-US/firefox/addon/launch-clipboard/ + https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/ or old http://menueditor.mozdev.org/ for placement and name customizing
"` <a>` tags" works perfectly from his majesty simple ctrl+c, "text links" works perfectly from \n-ending list of urls in clipboard (inner parser is buggy). optionally you can mimic tabutils and add amount of links

> unloaded state

it's easy to implement, just write or find out the function that creates unloaded tab
