### ISSUE TITLE
TUF在Firefox 44基本没法用了。。。

### ISSUE THREAD

**Issue by IceCreamQ** [yfdyh000/tabutils#64]
目前发现的问题：
1、新标签页设置项无效
2、鼠标滚轮切换标签页无效
3、标签页上右键，成堆的菜单
4、新标签页打开以下项目设置项无效
5、右键加载剪贴板中的URL设置项无效
其余没怎么使用不知道情况，有时间请验证并修复下。。。
环境是Win10 X64 + Firefox 44 Beta4 X86（从Beta1开始就这样了）

**Comment by yfdyh000** [comment]
试着依次回答下：
1、Mozilla的[问题](https://bugzilla.mozilla.org/show_bug.cgi?id=1118285)，41起去掉了设置项。加[扩展](https://addons.mozilla.org/firefox/search/?q=browser.newtab.url)吧。暂时没打算研究自带解决方案。
2、看上去正常，44b4 x64 + WIn10 x64。
3、这是个火狐的偶发bug，如果不是持续存在，重启一下火狐吧。
4、大概同1。
5、TU选项-鼠标-右键-新建标签页按钮，设置后看上去正常。

确实有三五个bug没修复，我也想修但好几个弄了半天卡在那里了，就坑了。39的全屏，43和44的后退菜单、添加全部为书签、书签属性面板空白（Nightly和Aurora，45起），都还没修。

**Comment by IceCreamQ** [comment]
经提醒，我用全新配置文件只安装TUF，上面提到的正常的，的确是正常的。但是又遇到了问题：
1、考虑可能是配置文件有问题，于是将可以正常使用的配置文件导出，再导入到原有的配置中，结果仍旧无法正常使用
2、考虑可能是扩展冲突，又将原配置文件中，除TUF外全部禁用重启，仍旧无法正常使用
3、将正常的配置文件导入原有的又立即导出，配置文件大小不一致
4、直接点击恢复默认设置，也是无法正常使用
。。。
然后我又试了一圈，最后发现在09-12版本（全新配置时在AMO安装的）是正常的，不知道什么时候更新的11-14版本（原有配置文件中的）有上述问题。

请问我们讨论的是同一个版本吗？【笑哭

**Comment by yfdyh000** [comment]
0912是正式和发在AMO的，1114只发在了Github的预览发布，我觉得是修好了后退菜单的问题，但几份报告说并没有修好，所以我目前并没有用……嗯，1114先隐藏掉了。
对了，1114并没有包含AMO的一个自动修复let，可能就会导致问题吧，所以别用了，用AMO吧。

**Comment by yfdyh000** [comment]
如仍有问题，请再报告。
