### ISSUE TITLE
搜索栏按回车后，不能后台新标签页显示。

### ISSUE THREAD

**Issue by xyzcheese** [yfdyh000/tabutils#66]
输入搜索关键字后，按回车，每次都是激活新标签页显示搜索结果。我的设置本来是不激活标签页的。感觉好像是升级成firefox 43.0.3后发现这个问题的。这应该是个bug。

**Comment by yfdyh000** [comment]
TU选项-标签页-打开标签页，第一个“搜索栏”，取消勾选了吗。我这里测试没问题。是其他扩展影响吗。

**Comment by xyzcheese** [comment]
设置上没问题。问题是关键字输入完后，手动按回车键，就会出现反映的问题。如果只是鼠标点击搜索按钮，那么标签页就是后台打开，不会激活。

**Comment by yfdyh000** [comment]
我用新配置尝试没有遇到所说的问题，是用了回车键。
对了，你的版本是AMO的09.12.1吗，Github上曾发布的11.14可能会有些未知问题。

**Comment by xyzcheese** [comment]
我用的版本确实是AMO的09.12.1。我的习惯基本是，以后台新建标签页的方式打开网页和搜索结果。另外我也新建配置了，只安装了AMO的09.12.1，按了回车后问题还是会出现。实在不明白为何我这里会异常。

**Comment by yfdyh000** [comment]
如仍有问题，请再报告。
