### ISSUE TITLE
Pin tab on FF Nightly

### ISSUE THREAD

**Issue by Mazzibig** [yfdyh000/tabutils#67]
After https://bugzilla.mozilla.org/show_bug.cgi?id=1220564 pin tab not correct visible.
I fix this by editing tabutils.js:2399
before
`var urls = [label.url for (label of labelArray)];`
after
`var urls = [for (label of labelArray) label.url];`

May be some need fix errors in other places of code

**Comment by yfdyh000** [comment]
Thank you, I see the problem. I would consider merging the changes.
