### ISSUE TITLE
Back/forward dropdown menus do not work

### ISSUE THREAD

**Issue by Jellby** [yfdyh000/tabutils#68]
When right-clicking or holding the back or forward arrows, a dropdown menu appears with the current tab's browsing history; however, selecting the items here does nothing.

I created a minimalist profile and installed this extension. With it disabled, the menus work as expected, with it enabled they don't, so I believe this is the culprit.

EDIT: Sorry, I just realized this is probably duplicate of #62, but it was not obvious from the title ;)

**Comment by yfdyh000** [comment]
Yes, it is a known issue since Firefox 43.

**Comment by viznov** [comment]
Do you plan to fix this issue, and when approx, if yes?

**Comment by yfdyh000** [comment]
I have to rewrite some code, but has not been successful after many attempts.
https://hg.mozilla.org/mozilla-central/rev/ca984908f2e5

**Comment by viznov** [comment]
It's a bad news for me, I like your TabUtils very much.
Thank you!

**Comment by White-Tiger** [comment]
well.. the most obvious fix is to replace

``` js
  TU_hookCode("gotoHistoryIndex",
    ["gBrowser.selectedTab", "tab", "g"],
    ["gBrowser", "tab.linkedBrowser", "g"],
    [/(?=let where)/, "let tab = gBrowser.mTabs[aEvent.target.parentNode.value];"]
  );
```

with

``` js
  TU_hookCode("gotoHistoryIndex",
    ["gBrowser.selectedTab", "tab", "g"],
    ["gBrowser", "tab.linkedBrowser", "g"],
    ["{", "let tab = gBrowser.selectedTab;"]
  );
```

mainly, `aEvent.target.parentNode.value` isn't valid anymore (the .value)

**Comment by yfdyh000** [comment]
@White-Tiger Thank you, it works! But it get incorrect behavior for "Session History Menu", I hope it works. Waiting for further research.

I may not be interested to study it in recent. Maybe I should ignore this point, just a perfectionist.

**Comment by White-Tiger** [comment]
which "Session History Menu"?

**Comment by yfdyh000** [comment]
TU Options - Mouse - *-click - On tabs: Session History Menu.

**Comment by White-Tiger** [comment]
and what kind of wrong behavior? The only difference I have (with or without "fix") is that the later also works for that menu... otherwise they seem to behave the same

**Comment by yfdyh000** [comment]
Click on an inactive tab, it get the menu for activity tab always.

**Comment by White-Tiger** [comment]
that happens even without the change.. so it's a different issue

**Comment by yfdyh000** [comment]
Works fine in Fx28 TU 1.6pre21. I think this change is changed the definition, it should get the click event target instead of the current tab.

**Comment by viznov** [comment]
Please release plugin fix if it's possible.

**Comment by White-Tiger** [comment]
@yfdyh000 well.. might not work for an old Firefox, yes, but the "Session History Menu" always opens for the active tab in newer versions anyway. So the menu needs to be fixed as well (and probably shouldn't use `gotoHistoryIndex()` or set the `gBrowser.selectedTab` temporarily)
Code that rewrites version dependent code like this, should use some kind of safety checks and versioning itself. (also means to document which version requires which code)

**Comment by Thomas279** [comment]
@White-Tiger can I insert your replacement manually - and where do I find it in the source code?

**Comment by yfdyh000** [comment]
@Thomas279 https://github.com/yfdyh000/tabutils/search?q=gotoHistoryIndex

**Comment by Thomas279** [comment]
@yfdyh000 thanx - I forgot how to search the code
@White-Tiger THANK YOU - IT WORKS !

**Comment by tedych** [comment]
Yes, White-Tiger's solution works.
Sometimes it's amazing how the official releases of things don't get fixed on time for such small things.
I moved back to TMP because of this, and despite this fix works, I'll stick with the competitor until something breaks there. Shouldn't "force" users to tinker around and manually craft fixes in code found in issue trackers. And I found this in the AMO comments, by accident.
And FF could stop supporting unsigned extensions at some time. It was rumored to happen earlier, not as of yet. Cannot tell for how long.

**Comment by White-Tiger** [comment]
my "solution" only fixes it for newer versions as yfdyh000 already mentioned. As it breaks some functionality of older Firefox versions.
Tab Mix Plus isn't an option for me though... I require the "restart tab" (unload tab) feature currently present in Tab Utilities which isn't present in Tab Mix Plus... And TMP is bloated, thus slower.

**Comment by viznov** [comment]
Could anyone explain where can I replace original code with White-Tiger's one? Need I file tabutils.js or maybe another? I can't find tabutils.js in my profile folder.

**Comment by tedych** [comment]
Ok, but why favor old versions (very old if 28 is the baseline) and not newer(st)?! It sounds a bit illogical to support old versions purposefully but not the latest ten or so. That said, I too want to use this lighter addon, but until and if TMP starts to act on me, I'll stick with it. Few months ago I ditched it after troubleshooting a slowness where a different addon proved to cause the problems. TMP does not feel slower per se, it only (maybe) might cause lags when FF accumulates 1-2 weeks or more, of uptime, eventually.

@viznov, decompress the manually downloaded addon (right click - save link as...) after renaming it to .zip. Then you will find the 140KB js file in the corresponding content folder. Then repack the same folder structure back to ZIP and rename back to XPI. Install manually in Addons in FF.

**Comment by viznov** [comment]
@tedych, thank you, it works!

**Comment by Guil211** [comment]
I modified the xp according to above instructions (download, convert xpi to zip, get the js file, convert to txt to edit in notepad, copy/paste white-tiger code in place of existing code, save file and rename from txt to js, overwrite the js file in the zip, re-convert zip back to xpi), but I can't even try it because FF thinks "it appears to be corrupt" and won't let me install. Did I miss something? How do I fix that?

Also, yfdyh000 it would be great if you could post the White-Tiger-modified version of the extension on the Mozilla website (maybe you've started this process already, I don't know), or at least here on github so guys like me don't tinker with programming stuff they don't understand in the slightest.

Cheers

**Comment by yfdyh000** [comment]
I was lucky enough to fixed it today, after several failed attempts.
Waiting for AMO review.

**Comment by Guil211** [comment]
Much appreciated yfdyh000! Just installed it, and so far so good, I've got the browsing history back! I haven't had the chance to test it further, but I'll post here again if I see anything.
Big thanks to you and White-Tiger!

**Comment by yfdyh000** [comment]
Note: the "Always show the menu" feature of Session History Menu is not work for now. Although seem very few people use the Session History Menu feature (and not including me).

**Comment by yfdyh000** [comment]
AMO approved. https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/
