### ISSUE TITLE
Strange problem with random tab closing

### ISSUE THREAD

**Issue by dachacha** [yfdyh000/tabutils#70]
Greetings!

I have very strange problem here. 
Sometimes for no reason when I click on **unfocused** tab while **firefox's window is unfocused** as well - the tab gets closed. Since I don't know exact reason for that, it's really hard to reproduce sometimes.

Here's short recorded fragment https://gfycat.com/PossibleDescriptiveBluefish 
What I'm doing here:
1) I click out of firefox window (it can be desktop or other window) to make it unfocused
2) Click on random unfocused tab
And thats it. As far as I know  _focused_ tab cannot be closed that way (and any tabs can't be closed if firefox's window is focused).

I'm also pretty sure it's not my mouse doubleclicking, I've run it through some tests, and by the way there's only one "ripple"  per click on the record. Though it's not mouse double clicking, it maybe problem exactly with doubleclick tab behavior(though I haven't tested yet with dclick-tab-close option disabled).

I'm currently on Firefox 43.0.4. I was previously on Firefox 38 and have never experienced anything like this.

//update: I changed double-click-on-tab behavior to "reload tab" and now tabs sometimes reloads on a single click. So that's definitely double click issue. But I don't think it is mouse problem. Tomorrow I will try to reproduce this with another mouse to be 100% sure.

**Comment by dachacha** [comment]
I changed double-click-on-tab behavior to "reload tab" and now tabs sometimes reloads on a single click. So that's definitely double click issue. But I don't think it is mouse problem. Tomorrow I will try to reproduce this with another mouse to be 100% sure.

**Comment by yfdyh000** [comment]
I occasionally have experience the problem too.
This may be an event handling problem, but I don't know the reasons.

**Comment by dachacha** [comment]
yfdyh000, I found exactly same issue on other addon's forum, so it is Firefox's problem. I will try to report this issue to them. Thank you

**Comment by yfdyh000** [comment]
Yes, I agree with that. Provide a Bugzilla link for follow will be appreciated.

**Comment by dachacha** [comment]
Here's bugzilla link https://bugzilla.mozilla.org/show_bug.cgi?id=1241103
