### ISSUE TITLE
Why not keep to ESR release cycle?

### ISSUE THREAD

**Issue by KrofaThegen** [yfdyh000/tabutils#77]
I have a suggestion.

Since this add-on is probably a side-work for you; why not just limit your labor to keeping Tab Utilities Fixed compatible with the upcoming 45 ESR release? 

This would limit your exposure to the nightmare of ever tightening release cycle of regular FireFox; and dedicated users will get the benefit of security updates.

You could even announce this on the add-on page so that people have a way of knowing that their installations are both secure and sure to work with TUfixed.

Thank you sooo much for keeping this add-on alive! I cannot imagine using ff without it - even browsing the net without it!

Best!

**Comment by yfdyh000** [comment]
Because I daily use the Beta channel, it's that simple.

In fact, this project does not fixed all of the major bug since Fx40, I am very willing, but there is not enough interest to study how to really fix them. Works structure of the code is very headache, I was able to find out why it's not working, but it is often very troublesome to repair by me, and no technical assistance...

**Comment by KrofaThegen** [comment]
How can we help you? What kind of time investment seems necessary for getting TU up to date?

Since your time is limited, it seems more realistic to me to limit your efforts to a longer lasting release like the ESR version. Why torture yourself with the daily betas and regular releases? Current ESR is at 38.6. It's security is up to date and it's already working with TUfixed. So if you were to prepare TUfixed for the upcoming 45 ESR release; you'd be good to go for a whole new ESR cycle - possibly a whole year.

In fact I think this would be a good strategy for most developers that support complex add-ons.

**Comment by yfdyh000** [comment]
It does not get better results, find out and fix all changes in ESR not easy than Beta, and it gets a more intense period, i.e. when the ESR upcoming.

The frequency of changes is not a trouble for the project, the difficulty is how to fix them at the technical level, in my opinion.

**Comment by KrofaThegen** [comment]
I understand that the work itself is not less. But isn't it the case that once you've fixed everything to work fully for the ESR; then you can have some rest while the main ESR program remains unchanged and only security fixes are done. 

This is what I am trying to explain; I'm trying to lower your work load over a year. Instead of trying to keep up with the crazy regular release cycle; you fix TU for ESR once a year.

**Comment by yfdyh000** [comment]
First of all, I will not leave the Beta channel at least for now, I have strong interests in the Beta, not just use this extension. Secondly, I will difficult to find out a problem from which release version if use ESR, which adds an extra step to find.

Anyway, thanks for your advice and concerns.

**Comment by KrofaThegen** [comment]
Well; no problem at all. I wish there were ways we could help you more in this effort...
