### ISSUE TITLE
tabutils prevents firefox from showing the content of pop-up windows /dialogue boxes 

### ISSUE THREAD

**Issue by JulianBo** [yfdyh000/tabutils#78]
There is a problem which I tracked down to Tab utilities fixed - Version 1.5.2015.09.12.1-let-fixed. I use Windows 10. 

Whenever I want to use a Pop-Up Window from Firefox (such as add keyword for search, new folder in bookmark-window), there is no content shown for this dialogue. The "Save-File-as" or "add Bookmark"-Windows work, though. 

![screenshot_dialogue_add_folder_bookmarks](https://cloud.githubusercontent.com/assets/9675438/13667794/9663562e-e6b8-11e5-9c98-145ad18d8ddb.PNG)

![screenshot_dialogue_add_search_keyword](https://cloud.githubusercontent.com/assets/9675438/13667723/2aa842d2-e6b8-11e5-8055-032e07a70f7b.PNG)

**Comment by JulianBo** [comment]
p.s. I use Firefox 45.0

**Comment by yfdyh000** [comment]
https://github.com/yfdyh000/tabutils/releases/tag/2016.03.20
