### ISSUE TITLE
 2016.03.20 0 Tab Stacking not working

### ISSUE THREAD

**Issue by VelvetShadows** [yfdyh000/tabutils#81]
With the latest update which disables tab move animation, this also disables tab stacking if you have it enabled. Can be fixed by re-enabling the tab move animation.

**Comment by narimiran** [comment]
I have 2016.03.22 and tab stacking works, but there's no arrow that was used for expand/collapse.

**Comment by yfdyh000** [comment]
@RandPC I don't see the tab stack have significant broken, can you provide a reproducible steps?
In addition, you can toggle the extensions.tabutils.disableTabMoveAnimation in about:config to restore this behavior.

@narimiran Thanks for your report, confirmed, since Fx46.

**Comment by yfdyh000** [comment]
@narimiran Sorry, it has been reported in #79, I miessed this issue and mistake the scope.

**Comment by yfdyh000** [comment]
Reopen if the issue is not resolved.
