### ISSUE TITLE
3.20 FF37 右键书签文件夹“在标签页打开书签组”只打开一个网页

### ISSUE THREAD

**Issue by kidzgy** [yfdyh000/tabutils#82]
用的是FF37版本，不知其他版本是否有这个问题

**Comment by yfdyh000** [comment]
感谢报告，已知问题，下一版本将修复。

**Comment by yfdyh000** [comment]
Version 1.5.2016.03.23 on https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/versions/ now.
