### ISSUE TITLE
No Longer Working with Pale Moon

### ISSUE THREAD

**Issue by Altaira** [yfdyh000/tabutils#85]
This extension worked as intended with Pale Moon, but after updating to the latest version it no longer works. I reverted back to the previous version TabUtilitiesFixed{1.5.2015.09.12.1-let-fixed} and it is working once again.

**Comment by yfdyh000** [comment]
Thanks for your report, I have seen it, I will find out why and fix it.

**Comment by Altaira** [comment]
Thank you!

**Comment by Altaira** [comment]
I'm stillhaving problems. Specifically:

1: I can't open a link in anew tab when middle-clicking

2: Tab Highlighting doesn't work under the Appearance option.

**Comment by yfdyh000** [comment]
Please wait for a new release. Prior to this, you can install the previous version from https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/versions/ and disable updates from the Add-ons Manager - Tab Utilities Fixed - More.

**Comment by Altaira** [comment]
Thanks for the help—I appreciate your efforts.

I already reverted back to the previous version and disabled updates.

**Comment by yfdyh000** [comment]
In fact, I guess the https://addons.mozilla.org/firefox/addon/tab-utilities/ is still fit to Pale Moon, what is the reason you moved to Fixed?

**Comment by Altaira** [comment]
I don't remember the exactreason, but I do remember that Tab Utilities 
no longer workedcorrectly, so I switched to Tab Utilities Fixedand it 
worked.

**Comment by yfdyh000** [comment]
Version 1.5.2016.03.23 on https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/versions/ now.

**Comment by Altaira** [comment]
Seems to be working now—thankyou for your efforts!
