### ISSUE TITLE
安装扩展后，后退/前进按钮出问题

### ISSUE THREAD

**Issue by DevSplash** [yfdyh000/tabutils#86]
按住后退/前进按钮，弹出前进/后退菜单，但点击菜单后无效
![bug](https://cloud.githubusercontent.com/assets/15691402/14239841/6c60b8e4-fa72-11e5-9c2f-4f1b639f8e87.png)
正常情况下，点击菜单后，网页可以后退/前进到指定的页面

**Comment by yfdyh000** [comment]
已知问题，一直没弄好。Duplicate of #68.
