### ISSUE TITLE
opens new tab when opening from address bar

### ISSUE THREAD

**Issue by coltrane58** [yfdyh000/tabutils#87]
I am running firefox 45.0.2 with 1.5.2016.03.23 on a Windows 10 system. I cannot stop firefox from opening a new tab when I enter a url on the addressbar. I have all of items in "Open new tabs for:" unchecked. 
help

thanks 
john

**Comment by yfdyh000** [comment]
I can't reproduce the problem using the same versions and new profile.

Troubleshoot your add-ons, as well as check the browser console (Ctrl+Shift+J) for related error messages.

**Comment by yfdyh000** [comment]
Reopen if you have more information.
