### ISSUE TITLE
Quite a few things broken on Firefox V47

### ISSUE THREAD

**Issue by kissglay** [yfdyh000/tabutils#89]
Seems like Firefox 47 breaking few things.
1. Style not working unless disabling then re-enabling them.
2. Multi-row tab bar not working.
3. Got extra space between stacked tab group and adjacent tabs / tab group.
Donno if there are any other problems as I just briefly tested it  on 47.

**Comment by yfdyh000** [comment]
I don't see these problems during Firefox 47b1~47 release and works for now.

**Comment by kissglay** [comment]
Sorry.
I found the problem.
This is because some very ancient legacy pref from the original tabutils left uncleaned.
Like `pref("extensions.tabutils.button.button_TotalCommander.image", "moz-icon:file://c:/tools/Totalcmd/TOTALCMD.EXE?size=16");
pref("extensions.tabutils.button.button_TotalCommander.path", "c:\\tools\\Totalcmd\\TOTALCMD64.EXE");
`
If leave any of these lines in pref.js, it breaks.
But these only starts breaking things since firefox V47.
