### ISSUE TITLE
"Failed to hook gBrowser.mTabContainer._notifyBackgroundTab" after issue #7 fixed

### ISSUE THREAD

**Issue by willyyoung** [yfdyh000/tabutils#9]
Firefox version: 36.0
Platform: Windows 7 x64 SP1
TU Fixed version: 2015.02.26

Got error message in error console:
Error: Failed to hook gBrowser.mTabContainer._notifyBackgroundTab: missing : after property id
Source: chrome://tabutils/content/tulib.js
Line: 28

雖然使用起來沒有啥問題 (俺不用 Vertical Tabbar 的)，還是來回報一下。辛苦了！ :)

**Comment by yfdyh000** [comment]
Thanks for the report, fixed.
