### ISSUE TITLE
"One-tab" stacks issue

### ISSUE THREAD

**Issue by reallyuniquename** [yfdyh000/tabutils#94]
Lets say I have a tab stack: [tab1|tab2|tab3]

If I close tab2 and tab3 then tab1 will become just a usual tab tab1 (at least visually).

The problem is tab1 still has all tab stack attributes like "group", "group-color", etc. It causes minor issues with custom styles since such tabs are still counted as tab stacks because of "group" attribute. Can you fix this?

Keep up the good work, I really appreciate you keep this addon alive.

**Comment by yfdyh000** [comment]
I see the related attributes of group is remain, e.g. Recolor Stack - set to #000000.
Even though the group leaving to one tab only (lost group characteristics), the attributes will retain and return once new tabs is created within the group.

I'm not sure whether you can exclusion group-counter="1" within CSS.

**Comment by reallyuniquename** [comment]
Is it possible to delete these group-attributes since one tab is no longer a tab stack?

**Comment by yfdyh000** [comment]
Like color and other attributes will be lost, so I don't want to remove them automatically.

`.tabbrowser-tab:not([group-counter="1"])` whether is enough?
Find `group-counter` to reference: https://github.com/yfdyh000/tabutils/search?q=group-counter

**Comment by reallyuniquename** [comment]
It is enough, thanks, yet it adds much extra code.

> I don't want to remove them automatically

Why not? How about removing just "group" attribute and keep other ones? It's no longer a tab stack anyway.

**Comment by yfdyh000** [comment]
Maybe it would be good. I'm working on the code.

Old text:
Simple reason: I don't want to create too much differences between the TU and TUF, if it is not a compatibility bug.

Remove the "group" attribute looks will normal, but it has a lot of references in the code, I difficult to ensure that it does not create other issues, there is no test coverage to ensure.
