### ISSUE TITLE
Ff48: Mouse scroll to focus tab broken

### ISSUE THREAD

**Issue by NickJH** [yfdyh000/tabutils#97]
Hi,
Ff updated to 48 last night and now you can no longer scroll between the tabs by hovering on the tab bar and using the mouse scroll wheel. Using v1.5.2016.07.31. on 32-bit Ff on Win10 x64.
Regards,
Nick

**Comment by yfdyh000** [comment]
I couldn't reproduce the problem. Using v1.5.2016.07.31 on 32 or 64-bit Firefox 48.0 on Win10 1607 x64, e10s on or off.
Can you provide more information? such as whether it is working in a new profile; Are there any JS errors regarding TU appears in Browser Console (Ctrl+Shift+J).

**Comment by NickJH** [comment]
All I see in the console is:

```
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()TypeError: this.pref.setCharPref is not a function
ieview.js:12:12
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
TypeError: this.pref.setCharPref is not a function
ieview.js:12:12
Empty string passed to getElementById().github-85be6e50566bf0d54eae1134d38efd7d13fa83ca927312c7bb10598ce7a08331.js:7:6536
Empty string passed to getElementById().frameworks-f5324fcaffda18bd9baabb17ff4c16660ac8a75108fae78eb335d2c5320a1d1d.js:9:7557
Error: Permission denied to access property "target"content.js:94:7
TypeError: NetworkError when attempting to fetch resource.(unknown)
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
```

I am also finding reload every is not working. I'll give a new profile a go.

**Comment by apogrebennyk** [comment]
Same problem on FF 48 on OSX 10.11.6.

**Comment by NickJH** [comment]
Sorry I'm really struggling with a new profile. I created one but it is blocking downloads from AMO. I'll have to try again later.

**Comment by yfdyh000** [comment]
@NickJH Use Ctrl+Shift+J to open Browser Console, instead of Web Console.

**Comment by NickJH** [comment]
```
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# insteadjquery.min.js:1
SyntaxError: expected expression, got '<'tapatalkdetect.js:1
Error: invalid version specifiedsdk.js:43:189
TypeError: this.pref.setCharPref is not a function
ieview.js:12:12
TypeError: this.pref.setCharPref is not a function
ieview.js:12:12
TypeError: this.pref.setCharPref is not a function
ieview.js:12:12
Key event not available on some keyboard layouts: key="c" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="u" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="p" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="f" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="l" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="k" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="t" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt,shift"browser.xul
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
```

`

**Comment by yfdyh000** [comment]
@NickJH `The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.` only appear in web console. Are you sure you copy from the Browser Console (Ctrl+Shift+J)?

**Comment by yfdyh000** [comment]
I also can't to reproduce it in Firefox 48.0 x64 on Lubuntu 14.04.
More information is needed, it may be due to preferences, system environment or other add-ons result.

**Comment by NickJH** [comment]
Any idea which script could block it? uBlock Origin? My prefs are attached.
[TUprefs.txt](https://github.com/yfdyh000/tabutils/files/400177/TUprefs.txt)

**Comment by yfdyh000** [comment]
Nope, in theory, it does not interfere with browser scripts.
I don't see this issue, after importing this configuration to TU and restart browser.

**Comment by NickJH** [comment]
I'm completely stuck. A new profile can't access AMO saying it has an invalid security certificate. I've tried disabling all extensions except this one and I still get the same problem. This old profile allows me to reinstall the addon so I don't understand why the new one won't. Have you any ideas?

**Comment by NickJH** [comment]
I've tried reinstalling Ff and TU but it has not helped. Removing IEView Lite, I now tee a TU error message in the console:

```
Could not read chrome manifest 'file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/chrome.manifest'.
Warning: attempting to write 4303 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
DEPRECATION WARNING: This path to Console.jsm is deprecated.  Please use Cu.import("resource://gre/modules/Console.jsm") to load this module.
You may find more details about this deprecation at: https://bugzil.la/912121
resource://gre/modules/devtools/Console.jsm 19 null
chrome://placescleaner/content/script.js 1 null

Deprecated.jsm:79
btwebui: attempting to register protocol
btwebui: enabling
Failed to hook FullScreen.mouseoverToggle: FullScreen.mouseoverToggle is not a function
tulib.js:28
Failed to hook FullScreen.mouseoverToggle: FullScreen.mouseoverToggle is not a function
tulib.js:28
Failed to hook FullScreen.showXULChrome: FullScreen.showXULChrome is not a function
tulib.js:28
ReferenceError: Application is not defined
script.js:256:1
Failed to hook gSessionHistoryObserver.observe: object is undefined
tulib.js:28
Empty string passed to getElementById().tabutils.js:3139:20
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
Warning: NetUtil.asyncFetch() requires the channel to have one of the security flags set in the loadinfo (see nsILoadInfo). Please create channel using NetUtil.newChannel()
Key event not available on some keyboard layouts: key="c" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="u" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="p" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="f" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="l" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="k" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="t" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt,shift"browser.xul
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
```

`

**Comment by yfdyh000** [comment]
@NickJH https://support.mozilla.org/en-US/kb/what-does-your-connection-is-not-secure-mean#w_the-certificate-is-not-trusted-because-the-issuer-certificate-is-unknown

I don't see a significant newer error. I will continue to follow it here, hoping someday encounter it.

**Comment by yfdyh000** [comment]
I'm sorry, I think I ignored and misunderstood the "focus".
I see, I will investigate it.

**Comment by NickJH** [comment]
Glad you've found it.

Note also ReloadEvery now never reloads and I've also lost the "Bookmark this Tab" context menu. I used to run MenuEditor extension to reorder the context menu but it is not signed so was disabled by Ff48. I have removed the MenuEditor extension completely and still don't get the context menu back. I know Bookmark All Tabs is also missing and I have a suspicion other context menu entries don't work but I have not checked properly.

**Comment by yfdyh000** [comment]
Yes, it is a known issue #95.
I did not find it. It may occur only when Firefox synced? ref: https://transvision.mozfr.org/?recherche=Bookmark+this+Tab&repo=aurora&sourcelocale=en-US.
I'm not sure it's situation, it is strange for now. But it is always in the context menu of tabs bar, at least. 
Thank you for reports.

**Comment by jetyu** [comment]
我也是这个问题，鼠标滚轮无法切换标签页。。。

**Comment by erdemuncuoglu** [comment]
FF48 on Debian 8 x64
I disabled all addons in my current profile ( not a clean profile)
This is the "browser console" output
`Could not read chrome manifest 'file:///usr/lib/firefox/chrome.manifest'.
Failed to hook FullScreen.mouseoverToggle: FullScreen.mouseoverToggle is not a function
tulib.js:28
Failed to hook FullScreen.mouseoverToggle: FullScreen.mouseoverToggle is not a function
tulib.js:28
Failed to hook FullScreen.showXULChrome: FullScreen.showXULChrome is not a function
tulib.js:28
Failed to hook gSessionHistoryObserver.observe: object is undefined
tulib.js:28
Empty string passed to getElementById().tabutils.js:3139:20
No chrome package registered for chrome://restclient/content/images/favicon.ico
Key event not available on some keyboard layouts: key="c" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="u" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="p" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="f" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="l" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="k" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="t" modifiers="accel,alt"browser.xul
Key event not available on some keyboard layouts: key="i" modifiers="accel,alt,shift"browser.xul
no element founddata::1:1
1471949037162   addons.productaddons    ERROR   Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]
Log.jsm:753
1471949037162   Toolkit.GMP ERROR   GMPInstallManager.simpleCheckAndInstall Could not check for addons: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no] Stack trace: checkCert()@resource://gre/modules/CertUtils.jsm:145 < downloadXML/</success()@resource://gre/modules/addons/ProductAddonChecker.jsm:121
Log.jsm:753
`
