### ISSUE TITLE
在设置 连接标签页打开单窗口模式后不能新建隐私窗口

### ISSUE THREAD

**Issue by withero** [yfdyh000/tabutils#98]
这个应该是个Bug吧。
普通窗口不能新建是正常的，但隐私窗口也不能新建了好像就不对了。

**Comment by yfdyh000** [comment]
嗯，好像是的，以前没这个功能所以作者没考虑这个。新建非e10s窗口也是（每夜版中）。
不知道怎么处理更好，弹个提示（拒绝新建/新建普通标签页），忽略设置新建窗口，新建隐私标签页（某些扩展支持，但开发有难度。可能调用某些扩展的接口会比较容易）。暂时没时间解决呢。

**Comment by withero** [comment]
不过还好TU现在大部分功能都正常。使用习惯了，TU不能用就麻烦了。
我也不知道用了什么扩展Fx48打不开多进程，刚又试了下，好像每一个扩展都有影响，这个多进程不知道有什么用，相当于要多进程就不能要扩展一样

**Comment by yfdyh000** [comment]
Fx48在有扩展时不会自动开e10s。about:config 中 browser.tabs.remote.autostart=true 就能启用了。
TU在e10s下目前未见新异常，因为不与网页交互。

**Comment by withero** [comment]
我设置上面的选项，不过在有扩展的情况下还是无法开启e01s，
在  about:support  中显示
多进程窗口     0/1（由附加组件禁用）
