### ISSUE TITLE
鼠标中键识别错误

### ISSUE THREAD

**Issue by wsxy162** [yfdyh000/tabutils#99]
设置中，鼠标-中键-新建标签页按钮 选中“操作A”。如果在浏览页面空白位置上点击中键，也会进行“操作A”。即扩展把页面中键点击误识别成按钮的中键点击了。

**Comment by yfdyh000** [comment]
请具体说一下操作A、浏览器版本、TU版本（确认是最新版就可以）、哪个页面。
使用Fx49b1和每夜版，鼠标-中键-保护标签页，未测得此问题。

**Comment by wsxy162** [comment]
这个问题还算是经常遇到的，我现在用的是 47.0 版本，TU 都是最新的，Firefox 前一两个版本的时候就碰到过这个问题了。写这条评论的时候没有这个问题了，不过出问题时试了下更改 鼠标-中键-新建标签页按钮 中的操作，在任何页面（新建、扩展、已载入的页面）空白出点击中键都会进行设置中的操作。

我会尝试如何复现这个问题。

**Comment by yfdyh000** [comment]
用47也未能重现。为什么要在空白处单击中键呢，“自动滚屏”吗，还是有其他扩展。

**Comment by wsxy162** [comment]
我触发的可能是这个问题 [https://bugzilla.mozilla.org/show_bug.cgi?id=366945](url)
由于当时中键的设置是 加载剪贴板中的URL ，让我以为是这个扩展的问题。

**Comment by yfdyh000** [comment]
可能是这样。你的是Linux吗，我在Win10上启用middlemouse.contentLoadURL也未重现。

**Comment by wsxy162** [comment]
是使用 Linux。汗，那个 bug 的讨论列表也有你。

**Comment by yfdyh000** [comment]
嗯，我不时在 Bugzilla 活跃，但近期少些了。
